name: CI

on:
  push:
    branches:
    #  - main
      - feature/CI_update
  pull_request:
    branches:
    #  - main
      - feature/CI_update

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: docker build -t my-app:latest .